<?php

return [
    App\Providers\AccountServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\BankIntegrationServiceProvider::class,
    App\Providers\BlockchainServiceProvider::class,
    App\Providers\CacheServiceProvider::class,
    App\Providers\ConsoleServiceProvider::class,
    App\Providers\CustodianServiceProvider::class,
    App\Providers\DemoServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\ExchangeRateProviderServiceProvider::class,
    App\Providers\ExchangeServiceProvider::class,
    App\Providers\ExternalExchangeServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\HelperServiceProvider::class,
    App\Providers\HorizonServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
    App\Providers\LendingServiceProvider::class,
    App\Providers\StablecoinServiceProvider::class,
    App\Providers\TelescopeServiceProvider::class,
    App\Providers\TestingServiceProvider::class,
    App\Providers\WalletServiceProvider::class,
    App\Providers\WebhookServiceProvider::class,
    L5Swagger\L5SwaggerServiceProvider::class,
];
