[program:finaegis-events-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=events --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/events-worker.log
stopwaitsecs=3600

[program:finaegis-ledger-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=ledger --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/ledger-worker.log
stopwaitsecs=3600

[program:finaegis-transactions-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=transactions --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/transactions-worker.log
stopwaitsecs=3600

[program:finaegis-default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/default-worker.log
stopwaitsecs=3600

[program:finaegis-liquidity-pools-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=liquidity_pools --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=3
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/liquidity-pools-worker.log
stopwaitsecs=3600

[program:finaegis-transfers-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=transfers --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/transfers-worker.log
stopwaitsecs=3600

[program:finaegis-mobile-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=mobile --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/mobile-worker.log
stopwaitsecs=3600

[program:finaegis-aux-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/yozaz/www/finaegis/core-banking-prototype-laravel/artisan queue:work --queue=broadcasts,webhooks,fraud-batch,exchange,proofs --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=yozaz
numprocs=2
redirect_stderr=true
stdout_logfile=/home/yozaz/www/finaegis/core-banking-prototype-laravel/storage/logs/aux-worker.log
stopwaitsecs=3600

[group:finaegis-workers]
programs=finaegis-events-worker,finaegis-ledger-worker,finaegis-transactions-worker,finaegis-default-worker,finaegis-liquidity-pools-worker,finaegis-transfers-worker,finaegis-mobile-worker,finaegis-aux-worker
priority=999